export const ALLOWED_FEATURE_ADD_NEW_ENQUIRY = ",ADD_NEW_ENQUIRY,";
export const ALLOWED_FEATURE_ENQUIRY_DELETE = ",ENQUIRY_DELETE,";
export const ALLOWED_FEATURE_ENQUIRY_LIST = ",ENQUIRY_LIST,";
export const ALLOWED_FEATURE_ENQUIRY_DETAILS = ",ENQUIRY_DETAILS,";
export const ALLOWED_FEATURE_ENQUIRY_EDIT = ",ENQUIRY_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_TRIAL = ",ADD_NEW_TRIAL,";
export const ALLOWED_FEATURE_TRIAL_DELETE = ",TRIAL_DELETE,";
export const ALLOWED_FEATURE_TRIAL_LIST = ",TRIAL_LIST,";
export const ALLOWED_FEATURE_TRIAL_DETAILS = ",TRIAL_DETAILS,";
export const ALLOWED_FEATURE_TRIAL_EDIT = ",TRIAL_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_MEMBER = ",ADD_NEW_MEMBER,";
export const ALLOWED_FEATURE_EDIT_MEMBER = ",MEMBER_EDIT,";
export const ALLOWED_FEATURE_DELETE_MEMBER = ",MEMBER_DELETE,";
export const ALLOWED_FEATURE_DETAILS_MEMBER = ",MEMBER_DETAILS,";
export const ALLOWED_FEATURE_MEMBER_LIST = ",MEMBER_LIST,";

export const ALLOWED_FEATURE_ADD_NEW_CUSTOMER = ",ADD_NEW_CUSTOMER,";
export const ALLOWED_FEATURE_CUSTOMER_DELETE = ",CUSTOMER_DELETE,";
export const ALLOWED_FEATURE_CUSTOMER_LIST = ",CUSTOMER_LIST,";
export const ALLOWED_FEATURE_CUSTOMER_DETAILS = ",CUSTOMER_DETAILS,";
export const ALLOWED_FEATURE_CUSTOMER_EDIT = ",CUSTOMER_EDIT,";

export const ALLOWED_FEATURE_MEMBER_MARK_ATTENDANCE = ",MEMBER_MARK_ATTENDANCE,";
export const ALLOWED_FEATURE_MEMBER_ATTENDANCE = ",MEMBER_ATTENDANCE,";

export const ALLOWED_FEATURE_CUSTOMER_MARK_ATTENDANCE = ",CUSTOMER_MARK_ATTENDANCE,";
export const ALLOWED_FEATURE_CUSTOMER_ATTENDANCE = ",CUSTOMER_ATTENDANCE,";

export const ALLOWED_FEATURE_ADD_NEW_PACKAGE = ",ADD_NEW_PACKAGE,";
export const ALLOWED_FEATURE_EDIT_PACKAGE = ",PACKAGE_EDIT,";
export const ALLOWED_FEATURE_DELETE_PACKAGE = ",PACKAGE_DELETE,";
export const ALLOWED_FEATURE_DETAILS_PACKAGE = ",PACKAGE_DETAILS,";
export const ALLOWED_FEATURE_PACKAGE_LIST = ",PACKAGE_LIST,";

export const ALLOWED_FEATURE_ADD_NEW_CATEGORY = ",ADD_NEW_CATEGORY,";
export const ALLOWED_FEATURE_CATEGORY_DELETE = ",CATEGORY_DELETE,";
export const ALLOWED_FEATURE_CATEGORY_LIST = ",CATEGORY_LIST,";
export const ALLOWED_FEATURE_CATEGORY_DETAILS = ",CATEGORY_DETAILS,";
export const ALLOWED_FEATURE_CATEGORY_EDIT = ",CATEGORY_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_PRODUCT = ",ADD_NEW_PRODUCT,";
export const ALLOWED_FEATURE_PRODUCT_DELETE = ",PRODUCT_DELETE,";
export const ALLOWED_FEATURE_PRODUCT_LIST = ",PRODUCT_LIST,";
export const ALLOWED_FEATURE_PRODUCT_DETAILS = ",PRODUCT_DETAILS,";
export const ALLOWED_FEATURE_PRODUCT_EDIT = ",PRODUCT_EDIT,";

export const ALLOWED_FEATURE_SALES_LIST = ",SALES_LIST,";
export const ALLOWED_FEATURE_SALES_DETAILS = ",SALES_DETAILS,";
export const ALLOWED_FEATURE_POSTPAID_BILL_LIST = ",POSTPAID_BILL_LIST,";
export const ALLOWED_FEATURE_BALANCE_PAYMENT_LIST = ",BALANCE_PAYMENT_LIST,";
export const ALLOWED_FEATURE_RENEWAL_LIST = ",RENEWAL_LIST,";

export const ALLOWED_FEATURE_ADD_NEW_USER = ",ADD_NEW_USER,";
export const ALLOWED_FEATURE_USER_DELETE = ",USER_DELETE,";
export const ALLOWED_FEATURE_USER_LIST = ",USER_LIST,";
export const ALLOWED_FEATURE_USER_DETAILS = ",USER_DETAILS,";
export const ALLOWED_FEATURE_USER_EDIT = ",USER_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_STAFF = ",ADD_NEW_STAFF,";
export const ALLOWED_FEATURE_STAFF_DELETE = ",STAFF_DELETE,";
export const ALLOWED_FEATURE_STAFF_LIST = ",STAFF_LIST,";
export const ALLOWED_FEATURE_STAFF_DETAILS = ",STAFF_DETAILS,";
export const ALLOWED_FEATURE_STAFF_EDIT = ",STAFF_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_TRAINER = ",ADD_NEW_TRAINER,";
export const ALLOWED_FEATURE_TRAINER_DELETE = ",TRAINER_DELETE,";
export const ALLOWED_FEATURE_TRAINER_LIST = ",TRAINER_LIST,";
export const ALLOWED_FEATURE_TRAINER_DETAILS = ",TRAINER_DETAILS,";
export const ALLOWED_FEATURE_TRAINER_EDIT = ",TRAINER_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_BRANCH = ",ADD_NEW_BRANCH,";
export const ALLOWED_FEATURE_BRANCH_DELETE = ",BRANCH_DELETE,";
export const ALLOWED_FEATURE_BRANCH_LIST = ",BRANCH_LIST,";
export const ALLOWED_FEATURE_BRANCH_DETAILS = ",BRANCH_DETAILS,";
export const ALLOWED_FEATURE_BRANCH_EDIT = ",BRANCH_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_EXPENSE = ",ADD_NEW_EXPENSE,";
export const ALLOWED_FEATURE_EXPENSE_DELETE = ",EXPENSE_DELETE,";
export const ALLOWED_FEATURE_EXPENSE_LIST = ",EXPENSE_LIST,";
export const ALLOWED_FEATURE_EXPENSE_DETAILS = ",EXPENSE_DETAILS,";
export const ALLOWED_FEATURE_EXPENSE_EDIT = ",EXPENSE_EDIT,";

export const ALLOWED_FEATURE_GENERAL_SETTINGS = ",GENERAL_SETTINGS,";

export const ALLOWED_FEATURE_ADD_NEW_MAIL = ",ADD_NEW_MAIL,";
export const ALLOWED_FEATURE_MAIL_DELETE = ",MAIL_DELETE,";
export const ALLOWED_FEATURE_MAIL_LIST = ",MAIL_LIST,";
export const ALLOWED_FEATURE_MAIL_DETAILS = ",MAIL_DETAILS,";
export const ALLOWED_FEATURE_MAIL_EDIT = ",MAIL_EDIT,";

export const ALLOWED_FEATURE_WHATSAPP_SETTINGS = ",WHATSAPP_SETTINGS,";

export const ALLOWED_FEATURE_ENQUIRY_SOURCE = ",ENQUIRY_SOURCE,";
export const ALLOWED_FEATURE_ENQUIRY_SOURCE_DELETE = ",ENQUIRY_SOURCE_DELETE,";
export const ALLOWED_FEATURE_ENQUIRY_TYPE = ",ENQUIRY_TYPE,";
export const ALLOWED_FEATURE_ENQUIRY_TYPE_DELETE = ",ENQUIRY_TYPE_DELETE,";

export const ALLOWED_FEATURE_BATCH_ADD = ",BATCH_ADD,";

export const ALLOWED_FEATURE_TAX_ADD = ",TAX_ADD,";
export const ALLOWED_FEATURE_TAX_GROUP_ADD = ",TAX_GROUP_ADD,";

export const ALLOWED_FEATURE_PAYMENT_TYPE = ",PAYMENT_TYPE,";
export const ALLOWED_FEATURE_PRIMARY_GOAL = ",PRIMARY_GOAL,";
export const ALLOWED_FEATURE_SECONDARY_GOAL = ",SECONDARY_GOAL,";
export const ALLOWED_FEATURE_HEALTH_INFO = ",HEALTH_INFO,";
export const ALLOWED_FEATURE_BODY_MEASUREMENT = ",BODY_MEASUREMENT,";
export const ALLOWED_FEATURE_TERMS_CONDITION = ",TERMS_CONDITION,";

export const ALLOWED_FEATURE_ADD_NEW_BRANCH_INVENTORY = ",ADD_NEW_BRANCH_INVENTORY,";
export const ALLOWED_FEATURE_BRANCH_INVENTORY_DELETE = ",BRANCH_INVENTORY_DELETE,";
export const ALLOWED_FEATURE_BRANCH_INVENTORY_LIST = ",BRANCH_INVENTORY_LIST,";
export const ALLOWED_FEATURE_BRANCH_INVENTORY_DETAILS = ",BRANCH_INVENTORY_DETAILS,";
export const ALLOWED_FEATURE_BRANCH_INVENTORY_EDIT = ",BRANCH_INVENTORY_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_SUPPLIER = ",ADD_NEW_SUPPLIER,";
export const ALLOWED_FEATURE_SUPPLIER_DELETE = ",SUPPLIER_DELETE,";
export const ALLOWED_FEATURE_SUPPLIER_LIST = ",SUPPLIER_LIST,";
export const ALLOWED_FEATURE_SUPPLIER_DETAILS = ",SUPPLIER_DETAILS,";
export const ALLOWED_FEATURE_SUPPLIER_EDIT = ",SUPPLIER_EDIT,";

export const ALLOWED_FEATURE_ADD_NEW_ROLE = ",ADD_NEW_ROLE,";
export const ALLOWED_FEATURE_ROLE_DELETE = ",ROLE_DELETE,";
export const ALLOWED_FEATURE_ROLE_LIST = ",ROLE_LIST,";
export const ALLOWED_FEATURE_ROLE_DETAILS = ",ROLE_DETAILS,";
export const ALLOWED_FEATURE_ROLE_EDIT = ",ROLE_EDIT,";

export const ALLOWED_FEATURE_WHATSAPP_BULK = ",WHATSAPP_BULK,";
export const ALLOWED_FEATURE_EMAIL_BULK = ",EMAIL_BULK,";


export const ALLOWED_FEATURE_DASHBOARD = ",DASHBOARD,";
export const ALLOWED_FEATURE_DASHBOARD_SALES = ",DASHBOARD_SALES,";
export const ALLOWED_FEATURE_DASHBOARD_POSTPAID_BILLS = ",DASHBOARD_POSTPAID_BILLS,";
export const ALLOWED_FEATURE_DASHBOARD_RENEWALS = ",DASHBOARD_RENEWALS,";
export const ALLOWED_FEATURE_DASHBOARD_MEMBERS = ",DASHBOARD_MEMBERS,";
export const ALLOWED_FEATURE_DASHBOARD_SALES_GRAPH = ",DASHBOARD_SALES_GRAPH,";
export const ALLOWED_FEATURE_DASHBOARD_LEAD_GRAPH = ",DASHBOARD_LEAD_GRAPH,";
export const ALLOWED_FEATURE_DASHBOARD_OTHRES = ",DASHBOARD_OTHRES,";
export const ALLOWED_FEATURE_DASHBOARD_RENEWALS_LIST = ",DASHBOARD_RENEWALS_LIST,";
export const ALLOWED_FEATURE_DASHBOARD_DUEBILLS_LIST = ",DASHBOARD_DUEBILLS_LIST,";
export const ALLOWED_FEATURE_DASHBOARD_BALANCE_PAYMNET_LIST = ",DASHBOARD_BALANCE_PAYMNET_LIST,";
export const ALLOWED_FEATURE_DASHBOARD_ENQUIRIES_LIST = ",DASHBOARD_ENQUIRIES_LIST,";
export const ALLOWED_FEATURE_DASHBOARD_TRIALS_LIST = ",DASHBOARD_TRIALS_LIST,";
